spring:
  datasource:
    url: jdbc:h2:~/coolshoesbatchdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: /Users/fabiomiyasato/Documents/filetodelete.txt

input:
  file: cadastro_pessoa.csv